packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/react-is': ^19.0.0
  '@sanity/client': ^7.6.0
  '@sanity/preview-url-secret': ^2.1.11
  '@sanity/types': 3.95.1-ui3.25.95f33c4bf6
  '@sanity/ui': 3.0.0-static.43
  '@sanity/vision': 3.95.1-ui3.25.95f33c4bf6
  babel-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
  react: 19.1.0
  react-dom: 19.1.0
  react-is: 19.1.0
  sanity: 3.95.1-ui3.25.95f33c4bf6
  styled-components: ^6.1.19
  typescript: 5.8.3